import { Link } from "react-router-dom";
const Footer = () => {
  return (
    <footer className="footer footer-center p-10 text-primary-content mt-20 bg-primary">
      <aside>
        <h1 className="text-2xl font-bold">Port Cats</h1>
        <img src="/logo.webp" alt="logo" className="rounded-full w-16" />
        <p className="font-bold">Developed by @sycrw and @lcarilla</p>
        <p>
          <Link to="https://github.com/sycrw/portcats">
            Contribute on Github
          </Link>
        </p>
        <p>
          This content is generated by contributors on Github. We welcome
          contributions from anyone interested. If you believe that your
          copyright has been infringed upon, please do not hesitate to reach out
          to us for resolution.
        </p>
      </aside>
    </footer>
  );
};

export default Footer;
